version: '3.8'

services:
    application:
        container_name: user-service_svc
        image: user-service:0.0.1
        ports:
            - "8080:8080"
        depends_on:
            - dbms
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dbms:5432/
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres

    dbms:
        image: 'postgres:latest'
        container_name: user-service_dbms
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 5s
            timeout: 3s
            retries: 30
